config/routes.rb
ParadaDeOnibusWeb::Application.routes.draw do

  resources :empresas

  resources :linhas do
    resources :horarios
    resources :itinerarios
  end

  resources :enderecos

  resources :bairros

  resources :cidades

  resources :estados

  devise_for :users

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  root :to => "linhas#index"

end

app/models/linha.rb
# -*- coding: utf-8 -*-
class Linha < ActiveRecord::Base

  default_scope :order => "nome ASC"

  belongs_to :empresa
  has_many :horarios
  has_many :itinerarios

  validates :numero, :presence => true
  validates :nome, :presence => true, :uniqueness => true

  def proximo_horario
    agora         = Time.now
    dia_da_semana = [1..5].include?(agora.wday) ? "u" : agora.wday == 6 ? "s" : "d"
    horarios      = Horario.where(:linha_id => id).where(:dia_da_semana => dia_da_semana).where("hora > ?", agora).order("hora ASC").partition {|h| h.sentido == "i"}
    ida, volta    = horarios[0].first, volta = horarios[1].first
    {
      :ida => (ida ? "#{ida.hora.hour}:#{ida.hora.min}" : nil),
      :volta => (volta ? "#{volta.hora.hour}:#{volta.hora.min}" : nil)
    }
  end

  def self.pesquisar bairro
    return nil unless bairro
    ja_pesquisado = Busca.where("texto = ?", bairro).count > 0
    parse_salvador(URI.escape(bairro.gsub("%",""))) unless ja_pesquisado
    Linha.where("nome ILIKE ?",bairro.insert(0,"%").insert(-1,"%"))
  end

  # TODO: implementar outras cidades
  # def self.parse cidade
  #   case cidade
  #   when "Salvador"
  #     parse_salvador
  #   end
  # end

  def self.parse_salvador linha
    return [] unless linha
    html = Nokogiri::HTML(open("http://www.stp.salvador.ba.gov.br/transporte/categorias/Onibus/consultar_linha.php?linha=#{linha}"))
    linhas = []
    cidade = Cidade.where(:nome => "Salvador").first
    estado = Estado.where(:nome => "Bahia").first
    html.css('.fundocadastrologin').each_with_index do |l, i|
      bairro = l.at('td[@width="238"]').text.split('-')
      linhas[i] = {
        :numero => l.at('td div').text,
	:nome 	=> l.at('td[@width="238"]').text
      }
    end
    Linha.create(linhas)
  end
  
end

app/controllers/linhas_controller.rb
class LinhasController < ApplicationController

  respond_to :html
  respond_to :xml, :json, :only => :index

  # GET /linhas
  # GET /linhas.xml
  # GET /linhas.json
  def index
    @linhas = (params && params[:nome] ? Linha.pesquisar(params[:nome]) : Linha.all)
    respond_to do |format|
      format.html { @linhas = @linhas.paginate(:page => params[:page] || 1, :per_page => 50)}
      format.any(:xml, :json) do
        formato = request.format.to_sym
        saida   = { :methods => [:proximo_horario], :only => [:id, :nome, :numero], :include => :empresa }
        render formato => @linhas.send("to_#{formato}", saida)
      end
    end
  end

  # GET /linhas/1
  def show
    @linha = Linha.find(params[:id])
    respond_with @linha
  end

  # GET /linhas/new
  def new
    @linha = Linha.new
  end

  # GET /linhas/1/edit
  def edit
    @linha = Linha.find(params[:id])
  end

  # POST /linhas
  def create
    @linha = Linha.new(params[:linha])
    respond_with(@linha) do |format|
      format.html { @linha.save ? redirect_to(linhas_path, :notice => 'Linha cadastrada com sucesso.') : render(:action => "new") }
    end
  end

  # PUT /linhas/1
  def update
    @linha = Linha.find(params[:id])
    respond_with(@linha) do |format|
      format.html { @linha.update_attributes(params[:linha]) ? redirect_to(linhas_path, :notice => 'Linha atualizada com sucesso.') : render(:action => "edit") }
    end
  end

  # DELETE /linhas/1
  def destroy
    @linha = Linha.find(params[:id])
    @linha.destroy
    redirect_to(linhas_url)
  end
end

app/helpers/linhas_helper.rb
module LinhasHelper
end

app/views/linhas/_form.html.erb
<%= simple_form_for(@linha, :html => { :class => :form }) do |f| %>
  <div class="fields">
    <%= f.input :numero, :wrapper_html => { :class => "group" }, :hint => 'Ex: 1234-A' %>
    <%= f.input :nome, :wrapper_html => { :class => "group" }, :hint => 'Ex: Rodoviária Circular - R1' %>
  <%= f.association :empresa, :label_method => :nome, :wrapper_html => { :class => "group" } %>
  </div>
  <div class="group navform wat-cf">
    <button class="button" type="submit">
      <%= image_tag("web-app-theme/icons/tick.png", :alt => t("web-app-theme.save", :default => "Save")) %> <%= t("web-app-theme.save", :default => "Save") %>
    </button>
    <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
    <%= link_to t("web-app-theme.cancel", :default => "Cancel"), linhas_path, :class => "text_button_padding link_button" %>
  </div>
<% end %>

app/views/linhas/_sidebar.html.erb
<div class="block notice">
  <div class="content">
   <%= form_tag linhas_path, :method => "get", :class => "form" do %>
    <div class="input">
      <%= label_tag :nome, "Pesquisar:" %>
      <%= text_field_tag :nome %>
    </div>
    <%= submit_tag "Ok" %>
   <% end %>
  </div>
</div>

app/views/linhas/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", linhas_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_linha_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_linha_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Linha</h2>
    <div class="inner">
      <%= render :partial => "form" %>
    </div>
  </div>
</div>
<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/linhas/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", linhas_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_linha_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Linhas</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
          <th><%= t("activerecord.attributes.linha.numero", :default => t("activerecord.labels.numero", :default => "Numero")) %></th>
          <th><%= t("activerecord.attributes.linha.nome", :default => t("activerecord.labels.numero", :default => "Nome")) %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @linhas.each do |linha| -%>
          <tr class="<%= cycle("odd", "even") %>">
            <td><%= linha.id %></td>
            <td><%= link_to linha.numero, linha_path(linha) %></td>
            <td><%= link_to linha.nome, linha_path(linha) %></td>
            <td class="last">
              <%= link_to "Horários", linha_horarios_path(linha) %> |
	      <%= link_to "Itinerário", linha_itinerarios_path(linha) %>
            </td>
          </tr>          
        <% end -%>
        <tr>
          <td colspan="5"><%= will_paginate @linhas if @linhas %></td>
        </tr>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions"></div>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/linhas/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", linhas_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_linha_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Linha</h2>
    <div class="inner">
      <%= render :partial => "form" %>
    </div>
  </div>
</div>
<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/linhas/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", linhas_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_linha_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", linha_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.linha.numero", :default => t("activerecord.labels.numero", :default => "Numero")) %>:</b>
          <%= @linha.numero %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.linha.nome", :default => t("activerecord.labels.nome", :default => "Nome")) %>:</b>
          <%= @linha.nome %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.linha.empresa_id", :default => t("activerecord.labels.empresa_id", :default => "Empresa")) %>:</b>
          <%= @linha.empresa.nome if @linha.empresa %>
        </p>

      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_linha_path(@linha), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), linha_path(@linha), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>