config/routes.rb
ParadaDeOnibusWeb::Application.routes.draw do

  resources :empresas

  resources :linhas do
    resources :horarios
    resources :itinerarios
  end

  resources :enderecos

  resources :bairros

  resources :cidades

  resources :estados

  devise_for :users

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  root :to => "linhas#index"

end

app/models/estado.rb
class Estado < ActiveRecord::Base

	has_many :cidades
	
	validates :nome, :presence => true, :uniqueness => true
	validates :uf,   :presence => true, :uniqueness => true
	
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  # GET /estados
  # GET /estados.xml
  def index
    @estados = Estado.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @estados }
    end
  end

  # GET /estados/1
  # GET /estados/1.xml
  def show
    @estado = Estado.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @estado }
    end
  end

  # GET /estados/new
  # GET /estados/new.xml
  def new
    @estado = Estado.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @estado }
    end
  end

  # GET /estados/1/edit
  def edit
    @estado = Estado.find(params[:id])
  end

  # POST /estados
  # POST /estados.xml
  def create
    @estado = Estado.new(params[:estado])

    respond_to do |format|
      if @estado.save
        format.html { redirect_to(@estado, :notice => 'Estado was successfully created.') }
        format.xml  { render :xml => @estado, :status => :created, :location => @estado }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @estado.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /estados/1
  # PUT /estados/1.xml
  def update
    @estado = Estado.find(params[:id])

    respond_to do |format|
      if @estado.update_attributes(params[:estado])
        format.html { redirect_to(@estado, :notice => 'Estado was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @estado.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.xml
  def destroy
    @estado = Estado.find(params[:id])
    @estado.destroy

    respond_to do |format|
      format.html { redirect_to(estados_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/views/estados/_form.html.erb
<%= simple_form_for(@estado, :html => { :class => :form }) do |f| %>
  <div class="fields">
		
        <%= f.input :nome, :wrapper_html => { :class => "group" }, :hint => 'Ex:' %>
    
        <%= f.input :uf, :wrapper_html => { :class => "group" }, :hint => 'Ex:' %>
      </div>
	<div class="group navform wat-cf">
		<button class="button" type="submit">
		  <%= image_tag("web-app-theme/icons/tick.png", :alt => t("web-app-theme.save", :default => "Save")) %> <%= t("web-app-theme.save", :default => "Save") %>
		</button>
		<span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
		<%= link_to t("web-app-theme.cancel", :default => "Cancel"), estados_path, :class => "text_button_padding link_button" %>
  </div>
<% end %>

app/views/estados/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", estados_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_estado_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_estado_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Estado</h2>
    <div class="inner">
      <%= render :partial => "form" %>
    </div>
  </div>
</div>
<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/estados/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", estados_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_estado_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Estados</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.estado.nome", :default => t("activerecord.labels.nome", :default => "Nome")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @estados.each do |estado| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= estado.id %>
          </td>
                    <td>
            <%= link_to estado.nome, estado_path(estado) %>
          </td>
                    <td>
            <%= l(estado.created_at) %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", estado_path(estado) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_estado_path(estado) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", estado_path(estado), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/estados/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", estados_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_estado_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Estado</h2>
    <div class="inner">
      <%= render :partial => "form" %>
    </div>
  </div>
</div>
<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/estados/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", estados_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_estado_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", estado_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.estado.nome", :default => t("activerecord.labels.nome", :default => "Nome")) %>:</b>
          <%= @estado.nome %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.estado.uf", :default => t("activerecord.labels.uf", :default => "Uf")) %>:</b>
          <%= @estado.uf %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_estado_path(@estado), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), estado_path(@estado), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>