config/routes.rb
ParadaDeOnibusWeb::Application.routes.draw do

  resources :empresas

  resources :linhas do
    resources :horarios
    resources :itinerarios
  end

  resources :enderecos

  resources :bairros

  resources :cidades

  resources :estados

  devise_for :users

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  root :to => "linhas#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Busbase</title>
    <%= stylesheet_link_tag "web-app-theme/base",
  "web-app-theme/themes/default/style", "web-app-theme/override", "desktop" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <div id="header">
	<h1><a href="/">Busbase</a></h1>
	<div id="user-navigation">
          <ul class="wat-cf">
            <li><a href="/logout" class="logout"><%= t("web-app-theme.logout", :default => "Sair") %></a></li>
          </ul>
	</div>
	<div id="main-navigation">
          <ul class="wat-cf">
	    <li><%= link_to "Linhas", 	linhas_path %></li>
	    <li><%= link_to "Bairros", 	bairros_path %></li>
	    <li><%= link_to "Cidades", 	cidades_path %></li>
	    <li><%= link_to "Estados", 	estados_path %></li>
	    <li><%= link_to "Empresas", empresas_path %></li>
          </ul>
	</div>
      </div>    
      <div id="wrapper" class="wat-cf">
	<div class="flash">
          <% flash.each do |type, message| -%>
            <div class="message <%= type %>">
              <p><%= message %></p>
            </div>
          <% end -%>
	</div>
	<div id="main">
          <%= yield %>
          <div id="footer">
            <div class="block">
              <p>Busbase, um software livre desenvolvido pelo grupo Android Brasil - Projetos</p>
            </div>      
          </div>
	</div>
	<div id="sidebar">
          <%= yield :sidebar %>
	</div>
      </div>    
    </div>
  </body>
</html>

app/views/layouts/sign.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parada de ônibus</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="box">
      <%= yield %>            
    </div>
  </div>
</body>
</html>