config/routes.rb
ParadaDeOnibusWeb::Application.routes.draw do

  resources :empresas

  resources :linhas do
    resources :horarios
    resources :itinerarios
  end

  resources :enderecos

  resources :bairros

  resources :cidades

  resources :estados

  devise_for :users

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  root :to => "linhas#index"

end

app/models/bairro.rb
class Bairro < ActiveRecord::Base

  belongs_to :cidade
  has_many :enderecos

  validates :nome, :presence => true, :uniqueness => { :scope => [:cidade_id] }
  validates :cidade_id, :presence => true

end

app/controllers/bairros_controller.rb
class BairrosController < ApplicationController
  # GET /bairros
  # GET /bairros.xml
  def index
    @bairros = Bairro.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bairros }
    end
  end

  # GET /bairros/1
  # GET /bairros/1.xml
  def show
		@bairro = Bairro.find(params[:id])
		
	  respond_to do |format|
	    format.html # show.html.erb
	    format.xml  { render :xml => @bairro }
	  end
	  
  end

  # GET /bairros/new
  # GET /bairros/new.xml
  def new
    @bairro = Bairro.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bairro }
    end
  end

  # GET /bairros/1/edit
  def edit
    @bairro = Bairro.find(params[:id])
  end

  # POST /bairros
  # POST /bairros.xml
  def create
    @bairro = Bairro.new(params[:bairro])

    respond_to do |format|
      if @bairro.save
        format.html { redirect_to(@bairro, :notice => 'Bairro was successfully created.') }
        format.xml  { render :xml => @bairro, :status => :created, :location => @bairro }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bairro.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bairros/1
  # PUT /bairros/1.xml
  def update
    @bairro = Bairro.find(params[:id])

    respond_to do |format|
      if @bairro.update_attributes(params[:bairro])
        format.html { redirect_to(@bairro, :notice => 'Bairro was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bairro.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bairros/1
  # DELETE /bairros/1.xml
  def destroy
    @bairro = Bairro.find(params[:id])
    @bairro.destroy

    respond_to do |format|
      format.html { redirect_to(bairros_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/bairros_helper.rb
module BairrosHelper
end

app/views/bairros/_form.html.erb
<%= simple_form_for(@bairro, :html => { :class => :form }) do |f| %>
  <div class="fields">
		
        <%= f.input :nome, :wrapper_html => { :class => "group" } %>
    
        <%= f.association :cidade, :wrapper_html => { :class =>
        "group" }, :label_method => :nome %>
      </div>
	<div class="group navform wat-cf">
		<button class="button" type="submit">
		  <%= image_tag("web-app-theme/icons/tick.png", :alt => t("web-app-theme.save", :default => "Save")) %> <%= t("web-app-theme.save", :default => "Save") %>
		</button>
		<span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
		<%= link_to t("web-app-theme.cancel", :default => "Cancel"), bairros_path, :class => "text_button_padding link_button" %>
  </div>
<% end %>

app/views/bairros/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", bairros_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_bairro_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_bairro_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Bairro</h2>
    <div class="inner">
      <%= render :partial => "form" %>
    </div>
  </div>
</div>
<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/bairros/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", bairros_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_bairro_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Bairros</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.bairro.nome", :default => t("activerecord.labels.nome", :default => "Nome")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @bairros.each do |bairro| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= bairro.id %>
          </td>
                    <td>
            <%= link_to bairro.nome, bairro_path(bairro) %>
          </td>
                    <td>
            <%= l(bairro.created_at) %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", bairro_path(bairro) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_bairro_path(bairro) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", bairro_path(bairro), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/bairros/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", bairros_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_bairro_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Bairro</h2>
    <div class="inner">
      <%= render :partial => "form" %>
    </div>
  </div>
</div>
<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/bairros/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", bairros_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_bairro_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", bairro_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.bairro.nome", :default => t("activerecord.labels.nome", :default => "Nome")) %>:</b>
          <%= @bairro.nome %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.bairro.cidade_id", :default => t("activerecord.labels.cidade_id", :default => "Cidade")) %>:</b>
          <%= @bairro.cidade_id %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_bairro_path(@bairro), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), bairro_path(@bairro), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>